public enum EventType {
    DOOR_UNLOCKED, VENT_OPENED, CAMERA_DISABLED, KEYPAD_BYPASSED,

    GUARD_DETECTED, ALARM_TRIGGERED, HIGH_STRESS, HIGH_BPM,

    NEW_ROOM, POWER_FLUCTUATION, WATER_USED, MEDKIT_USED, REST_TAKEN,

    LOW_TURN_COUNT,
}
